from pystac import (
    Link,
    Collection,
    Extent,
    SpatialExtent,
    TemporalExtent,
    Provider,
    Summaries,
)
from datetime import datetime, timezone
from dep_collections.utils import WMS_URL

dep_ls_wofs_extent = Extent(
    SpatialExtent([[-180, -90, 180, 90]]),
    TemporalExtent([[datetime(1980, 1, 1, 0, 0, 0, 0, timezone.utc), None]]),
)

# Create a Collection
dep_ls_wofs_summary_alltime = Collection(
    id="dep_ls_wofs_summary_alltime",
    description="This dataset summarises long-term surface water observations across the Pacific region. It represents the frequency of water presence across all available observations, highlighting persistent and seasonal water bodies. The dataset supports hydrological analysis and environmental monitoring.\n\nLineage:\nGenerated by aggregating all Landsat-based water observations into a long-term occurrence metric.\n\nProcessing level:\nSummary / Statistical Product\n\nDataset type:\nMulti-year summary",
    title="Water Observations from Space (WOfS) All-Time Summary (Landsat, 30 m)",
    extent=dep_ls_wofs_extent,
    license="CC-BY-4.0",
    keywords=["surface water", "water occurrence", "water frequency"],
    providers=[
        Provider(
            name="Digital Earth Pacific",
            roles=["processor", "host"],
            url="https://digitalearthpacific.org",
        ),
        Provider(
            name="USGS",
            roles=["producer", "processor", "licensor"],
            url="https://www.usgs.gov/landsat-missions/landsat-collection-2-level-2-science-products",
        ),
        Provider(name="NASA", roles=["licensor"], url="https://www.nasa.gov/"),
    ],
    summaries=Summaries(
        {
            "gsd": [30],
            "eo:bands": [
                {
                    "name": "count_clear",
                    "description": "Count of clear observations",
                    "min": 0,
                    "max": 32767,
                    "nodata": -999,
                },
                {
                    "name": "count_wet",
                    "description": "Count of observations that are water",
                    "min": 0,
                    "max": 32767,
                    "nodata": -999,
                },
                {
                    "name": "frequency",
                    "description": "Frequency of water observations",
                    "min": 0,
                    "max": 1,
                    "nodata": "nan",
                },
                {
                    "name": "frequency_masked",
                    "description": "Frequency of water observations, with ocean masked",
                    "min": 0,
                    "max": 1,
                    "nodata": "nan",
                },
            ],
            "platform": ["landsat-5", "landsat-7", "landsat-8", "landsat-9"],
        },
    ),
)


dep_ls_wofs_summary_alltime.add_link(
    Link(
        rel="wms",
        target=WMS_URL,
        media_type="application/vnd.ogc.wms_xml",
        title="WMS Service for this Collection",
        extra_fields={
            "wms:layers": ["wofs_ls_summary_alltime"],
            "wms:styles": ["legacy_wofs_summary_alltime_frequency_masked", "wofs_summary_alltime_frequency_masked", "legacy_wofs_summary_alltime_frequency", "wofs_summary_alltime_frequency", "wofs_summary_alltime_wet", "wofs_summary_alltime_clear"],
            "wms:dimensions": {},
        },
    )
)
