from datetime import datetime, timezone

from pystac import (
    Link,
    Collection,
    Extent,
    Provider,
    SpatialExtent,
    Summaries,
    TemporalExtent,
)
from dep_collections.utils import WMS_URL

dep_s1_geomad_extent = Extent(
    SpatialExtent([[-180, -90, 180, 90]]),
    TemporalExtent([[datetime(1980, 1, 1, 0, 0, 0, 0, timezone.utc), None]]),
)

S1_BANDS = [
    "B02",
    "B03",
    "B04",
    "B05",
    "B06",
    "B07",
    "B08",
    "B8A",
    "B11",
    "B12",
]
MAD_BANDS = [("emad", "Euclidean"), ("smad", "Spectral"), ("bcmad", "Bray-Curtis")]


# Create a Collection
dep_s1_geomad = Collection(
    id="dep_s1_geomad",
    description="This dataset provides annual radar-based composite imagery derived from Sentinel-1 observations across the Pacific region. It summarises multi-temporal backscatter data into a representative annual dataset, independent of cloud cover. The dataset supports monitoring of land, water, and environmental change.\n\nLineage:\nGenerated by aggregating multi-temporal Sentinel-1 SAR observations into annual geometric median composites.\n\nProcessing level:\nComposite\n\nDataset type:\nAnnual composite",
    title="Annual Radar Composite (Sentinel-1, GeoMAD, 10 m)",
    extent=dep_s1_geomad_extent,
    license="CC-BY-4.0",
    keywords=["radar", "synthetic aperture radar", "composite"],
    providers=[
        Provider(
            name="Digital Earth Pacific",
            roles=["processor", "host"],
            url="https://digitalearthpacific.org",
        ),
        Provider(
            name="Microsoft",
            roles=["host"],
            url="https://microsoft.com",
        ),
        Provider(
            name="ESA",
            roles=["producer", "licensor"],
            url="https://sentinel.esa.int/web/sentinel/missions/sentinel-2",
        ),
    ],
    summaries=Summaries(
        {
            "gsd": [10],
            "eo:bands": [
                dict(
                    name=band,
                    common_name=band,
                    description=f"Median for {band} band",
                    min=0,
                    max=1,
                    nodata="nan",
                )
                for band in S1_BANDS
            ]
            + [
                dict(
                    name=f"mean_{band}",
                    common_name=band,
                    description=f"Mean for {band} band",
                    min=0,
                    max=1,
                    nodata="nan",
                )
                for band in S1_BANDS
            ]
            + [
                dict(
                    name=f"stdev_{band}",
                    common_name=band,
                    description=f"Standard deviation for {band} band",
                    min=0,
                    max=1,
                    nodata="nan",
                )
                for band in S1_BANDS
            ]
            + [
                dict(
                    name=band[0],
                    common_name=f"{band[1]} MAD",
                    description=f"{band[1]} median absolute deviations across all bands",
                    min=0,
                    max=1,
                    nodata="nan",
                )
                for band in MAD_BANDS
            ]
            + [
                dict(
                    name="count",
                    common_name="Count clear",
                    description="Count of clear observations",
                    min=0,
                    max=250,
                    nodata=0,
                )
            ],
            "platform": ["Sentinel-1A", "Sentinel-1B"],
        },
    ),
)


dep_s1_geomad.add_link(
    Link(
        rel="wms",
        target=WMS_URL,
        media_type="application/vnd.ogc.wms_xml",
        title="WMS Service for this Collection",
        extra_fields={
            "wms:layers": ["dep_s1_geomad"],
            "wms:styles": ["vv_vh_vh_over_vv", "vv", "vh", "stdev_vv", "stdev_vh", "mean_vv", "mean_vh", "count", "arcsec_smad", "log_emad", "log_bcmad"],
            "wms:dimensions": {},
        },
    )
)
