from pystac import (
    Link,
    Collection,
    Extent,
    SpatialExtent,
    TemporalExtent,
    Provider,
    Summaries,
)
from datetime import datetime, timezone

from dep_collections.utils import WMS_URL

dep_ls_fc_extent = Extent(
    SpatialExtent([[-180, -90, 180, 90]]),
    TemporalExtent([[datetime(1980, 1, 1, 0, 0, 0, 0, timezone.utc), None]]),
)

# Create a Collection
dep_ls_fc_summary_annual = Collection(
    id="dep_ls_fc_summary_annual",
    description="This dataset provides annual summaries of fractional land cover derived from Landsat imagery across the Pacific region. It aggregates scene-based observations into yearly statistical measures such as percentiles and counts of valid observations. The dataset supports long-term environmental monitoring, trend analysis, and land-use change assessment.\n\nLineage:\nGenerated by aggregating Landsat fractional cover observations into annual statistical summaries.\n\nProcessing level:\nSummary / Statistical Product\n\nDataset type:\nAnnual time series",
    title="Fractional Land Cover Annual Summary (Landsat, 30 m)",
    extent=dep_ls_fc_extent,
    license="CC-BY-4.0",
    keywords=["fractional cover", "bare soil", "vegetation"],
    providers=[
        Provider(
            name="Digital Earth Pacific",
            roles=["processor", "host"],
            url="https://digitalearthpacific.org",
        ),
        Provider(
            name="Amazon",
            roles=["host"],
            url="https://aws.amazon.com",
        ),
        Provider(
            name="USGS",
            roles=["producer", "processor", "licensor"],
            url="https://www.usgs.gov/landsat-missions/landsat-collection-2-level-2-science-products",
        ),
        Provider(name="NASA", roles=["licensor"], url="https://www.nasa.gov/"),
    ],
    summaries=Summaries(
        {
            "gsd": [30],
            "eo:bands": [
              {
                "name": "bs_pc_10",
                "common_name": "10th percentile of bare soil percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "bs_pc_50",
                "common_name": "50th percentile of bare soil percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "bs_pc_90",
                "common_name": "90th percentile of bare soil percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "pv_pc_10",
                "common_name": "10th percentile of photosynthetic vegetation percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "pv_pc_50",
                "common_name": "50th percentile of photosynthetic vegetation percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "bs_pc_90",
                "common_name": "90th percentile of photosynthetic vegetation percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "npv_pc_10",
                "common_name": "10th percentile of non-photosynthetic vegetation percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "npv_pc_50",
                "common_name": "50th percentile of non-photosynthetic vegetation percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "npv_pc_90",
                "common_name": "90th percentile of non-photosynthetic vegetation percentage",
                "description": "",
                "min": 0,
                "max": 127,
                "nodata": 255
              },
              {
                "name": "count_valid",
                "common_name": "Count of clear and valid observations",
                "description": "",
                "min": 0,
                "max": 32767
              },
              {
                "name": "qa",
                "common_name": "quality assurannce band",
                "description": "",
                "min": 0,
                "max": 2
              }
                ],
            "platform": ["landsat-5", "landsat-7", "landsat-8", "landsat-9"],
        },
    ),
)


dep_ls_fc_summary_annual.add_link(
    Link(
        rel="wms",
        target=WMS_URL,
        media_type="application/vnd.ogc.wms_xml",
        title="WMS Service for this Collection",
        extra_fields={
            "wms:layers": ["dep_ls_fc_summary_annual"],
            "wms:styles": ["fc_rgb", "green_veg_10", "green_veg_50", "green_veg_90", "non_green_veg_10", "non_green_veg_50", "non_green_veg_90", "bare_ground_10", "bare_ground_50", "bare_ground_90"],
            "wms:dimensions": {},
        },
    )
)
